### PR TITLE
23: Global setup for Playwright, and some basic Playwright UI tests 

### PR DESCRIPTION
**Pull request by adigidh**
fixes https://github.com/instructlab/ui/issues/23

Summary of changes:
- Setup Playwright (installed packages, setup configuration)
- Created a simple setup test that performs a real login with an e2e account and saves the storage state so the next tests can run in an authenticated state. Using env variables for username, and password so these can be supplied from the user. 
- Basic tests for login page
- NPM scripts for execution on local
- Docs in development markdown for running these tests locally

Example report after running the tests locally:
image

### CODE REVIEW

**Comment by vishnoianil** [comment]
@adigidh Exited to see this PR. Thanks for pushing this. Let me know if this PR is ready for review. 
Didn't look at it yet because it's in draft, so I am assuming it's still work in progress.

**Comment by adigidh** [comment]
> @adigidh Exited to see this PR. Thanks for pushing this. Let me know if this PR is ready for review. Didn't look at it yet because it's in draft, so I am assuming it's still work in progress.

@vishnoianil : Sent you a DM last week. Maybe this PR is good for first pass?
I'll resolve the conflicts on this one, and open it up for review.

**Comment by vishnoianil** [comment]
> > @adigidh Exited to see this PR. Thanks for pushing this. Let me know if this PR is ready for review. Didn't look at it yet because it's in draft, so I am assuming it's still work in progress.
> 
> @vishnoianil : Sent you a DM last week. Maybe this PR is good for first pass? I'll resolve the conflicts on this one, and open it up for review.

@adigidh PR looks good to me. Can you please add instructions for running the test cases in the development doc in docs directory. Once you update the docs, PR it good for merge, so please mark it ready for review.

**Comment by adigidh** [comment]
re: https://github.com/instructlab/ui/pull/254#issuecomment-2428340768

Thanks for the feedback @vishnoianil. Made some updates, and opened it up for review

**Comment by vishnoianil** [comment]
> re: [#254 (comment)](https://github.com/instructlab/ui/pull/254#issuecomment-2428340768)
> 
> Thanks for the feedback @vishnoianil. Made some updates, and opened it up for review

@adigidh We need to cherry-pick this to release-1.0 branch as well. Do you want me to squash the commits and merge ? Or do you want to keep the commit history (more work for cherry-pick). ?

**Review by vishnoianil — APPROVED** [review]

**Comment by adigidh** [comment]
> > re: [#254 (comment)](https://github.com/instructlab/ui/pull/254#issuecomment-2428340768)
> > Thanks for the feedback @vishnoianil. Made some updates, and opened it up for review
> 
> @adigidh We need to cherry-pick this to release-1.0 branch as well. Do you want me to squash the commits and merge ? Or do you want to keep the commit history (more work for cherry-pick). ?

@vishnoianil : Either way is okay. Can be done along the lines of the usual project workflow 👍

**Comment by vishnoianil** [comment]
@adigidh Squashed and merged. Can you please cherry-pick it to the release-1.0 branch as well.

**Pull request merged**
