### PR TITLE
refactor image workflows to parallel matrix

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
This PR, while does not speedup our workflows, makes it considerably less code, and easier to update. We should consider if we want something like this conceptually.

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
going to move this as an upstream pr for testing purposes

**Comment by Gregory-Pereira** [comment]
moved to: #364

**Comment by Gregory-Pereira** [comment]
For store and key example see: https://github.com/orgs/community/discussions/26302#discussioncomment-3251298

**Review by vishnoianil — APPROVED** [review]
LGTM

**Pull request merged**
