### PR TITLE
Created Metrics job

### PR DESCRIPTION
**Pull request by samarpita-bhaumik**
Create openshift manifest for Metrics job or cronjob #269

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
Can we convert this to a draft? The implementation should include the resources to build the image itself and to deploy it. Happy to sync on this if there is any confusion here.

**Comment by samarpita-bhaumik** [comment]
@Gregory-Pereira can you please elaborate, on the implementation of which you are talking about? I will make the changes and update the PR.

**Comment by Gregory-Pereira** [comment]
Applogies for the late response, I would love to help explain this! Particularly what I am reffering to is that this implementation is theoretical at this point, [see code](https://github.com/instructlab/ui/pull/379/files#diff-ee9cc496653ec0ed88b44ee699b4fb7495465954f3853551744874f86c9bfd21R13-R14):
```yaml
            image: your-image:tag
            command: ["/bin/sh", "-c", "your-metrics-command"]
```
We dont currently have the image for gathering the metrics, we will need to create a container image that will do this for us. In addition to this, its typically considered best practice to include other manifests to properly scope the permissions of the job / cronjob in the form of a `serviceAccount`, `Role` or `clusterRole`, and `roleBinding` or `clusterRoleBinding` (however if you want we can always implement this in later PRs, and run the job with permissions attributed to the native `default` SA that runs all default workloads. So to recap, we need to:

1.  Create the container image via a containerfile that we will run in the openshift cluster to send these metrics somewhere
2. Create the CI workflow that will publish this container image to our GHCR.io and Quay.io registries
3.  Move the [metrics cronjob](https://github.com/instructlab/ui/pull/379/files#diff-ee9cc496653ec0ed88b44ee699b4fb7495465954f3853551744874f86c9bfd21) that you implemented to the correct path. I believe this should be the [QA manifests deployment path](https://github.com/instructlab/ui/tree/main/deploy/k8s/overlays/openshift/qa), since we deploy production and we do not expect users to do this themselves, we don't need to collect deployment metrics there - those metrics will be built into the TS code ([see issue](https://github.com/instructlab/ui/issues/281)). However A strong arguement could also be made to move these to the [base manfiests](https://github.com/instructlab/ui/tree/main/deploy/k8s/base) so they get applied in both prod or QA even if it is a little overkill.
4. (OPTIONAL) Create a Service account for the job, and accurately scoped RBAC. On Openshift, there are some settings you have to check if that cluster has telemetry enabled otherwise its illegal to send those metrics. These checks plus RBAC have been configured into the [securesign's segment backup job](https://github.com/securesign/segment-backup-job) which is why I suggested going this direction, but any implementation that checks for those values is fine by me.

I know there is a lot here, but this is meant as background context to help. We can start piece by piece, and perhaps I should move this to an epic and break it down into more granular pieces. I will consult @vishnoianil and @nerdalert on scoping this accurately

**Comment by Gregory-Pereira** [comment]
Actually lets hold on the segment implementation. I would like to have the metrics from deployment and the metrics from the UI code (#281) go to the same place. Ill talk with Oleg and figure out which service we want to go with.

**Comment by Gregory-Pereira** [comment]
Im creating the base metrics deployment in #391, so we can pick this up as soon as that merges.

**Comment by samarpita-bhaumik** [comment]
@Gregory-Pereira yes I am interested.

**Pull request closed without merging**
