### PR TITLE
Argocd deployment

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
cc @vishnoianil and @nerdalert 
Addresses: #235 

Goals of this PR:
- setup basics of argocd deployment
- create argocd applications for prod, staining, and the sealed secrets operator, which  we will eventually move to for secret management
- manage prod deployment via renovate which will update the deployment manifests with the latest release

### CODE REVIEW

**Comment by vishnoianil** [comment]
@Gregory-Pereira awesome, love it. Is it good to go ?

**Comment by Gregory-Pereira** [comment]
Not quite, still testing the manifests in the cluster. Should have the base stuff ready by end of week

**Comment by vishnoianil** [comment]
> Not quite, still testing the manifests in the cluster. Should have the base stuff ready by end of week

cool. sounds good. 

Just sharing some info, in case it's helpful. 

Images from the main branch is pushed with the tag `main`.
images from the release-1.0 branch is pushed with the tag `release-1.0.
Once we cut the release based on the release-1.0 branch, it creates a tag (eg v1.0.0-beta.3), and the image for this release is pushed with the tag v1.0.0-beta.3 and also as `latest` tag. 

Production deployment always pulls the latest tag, which will be generated on every release cut. So the argo-cd pipeline should trigger whenever new release is cut.
QA deployment should pull the images with `main` tag.

**Review by vishnoianil — APPROVED** [review]
LGTM! awesome work! Thanks @Gregory-Pereira

**Pull request merged**
