### PR TITLE
Improve the UI login page

### LINKED ISSUE #76: Improve the github login UI
Currently the login page has small github icon that takes you for github authentication. This is not very intuitive, folks generally endup trying the github credential in the username/password and it obviously fails. 

We need to either add text "Login with (github icon)" or something better to make it more intuitive.

### PR DESCRIPTION
**Pull request by vishnoianil**
Production login page entire redesigned. It only provides the github login option.

To use the dev login, set the IL_UI_DEPLOYMENT env variable to "dev" in .env file. This will display the old login page with user name/password and github login as well.

Fixes #76

### CODE REVIEW

**Comment by vishnoianil** [comment]
Screenshot 2024-08-14 at 1 35 22 AM

Above snapshot shows how UI login page will look like in the production deployment.

**Comment by vishnoianil** [comment]
@Misjohns Please review the above snapshot and let me know if you have any feedback.

**Comment by Misjohns** [comment]
@vishnoianil On the original log in there are 3 links: Terms of Use, Help, and Privacy Policy. All 3 link to [InstructLab.ai](https://instructlab.ai/) where I do not see any mention of these. I think we should either:

1. Link to the [InstructLab GitHub project](https://github.com/instructlab) instead, linking to the [ReadMe.md](https://github.com/instructlab/community/blob/main/README.md) page and add that content there or 
2. Remove the links we display on the log in and just display "By signing in, you agree to our terms of service and privacy policy." as plain text.

Also, we should make the link color white with underlines since the contrast with the blue links on the purple is horrible.

**Review by nerdalert — APPROVED** [review]
🥳 lgtm

**Pull request merged**
