### PR TITLE
Enhance the responsiveness of the login experience

### PR DESCRIPTION
**Pull request by samarpita-bhaumik**
I updated the githublogin.tsx by removing the Page and PageSection tags, replacing them with div tags. Additionally, I modified the githublogin.css to include both vertical and horizontal scrolling, ensuring the page adapts to any window size.

**Issue resolved by this Pull Request:**
Resolves # 164

**These are the screenshots when the window is minimized to the size of the mobile view:** 

image

image

### CODE REVIEW

**Review by aevo98765 — APPROVED** [review]
LGTM! Nice work @samarpita-bhaumik .

**Comment by aevo98765** [comment]
Hi @samarpita-bhaumik, would you be able to run `npm run pretty` and then commit the changes. This should fix the linting issues. I will then approve and merge. Thanks!

**Review by aevo98765 — CHANGES_REQUESTED** [review]
Linting

**Comment by samarpita-bhaumik** [comment]
@aevo98765 due to merging of pull requests I am getting merge conflicts in almost 40 files. It is becoming difficult for me to solve all the conflicts. Can I raise a fresh PR with my changes?

**Comment by samarpita-bhaumik** [comment]
@aevo98765 can you please check now. Is it okay?

**Comment by aevo98765** [comment]
Still linting errors. If you run `npm run lint` you should see if there are any issues that exist with your code.

It should mirror the attachment
Screenshot 2024-10-01 at 17 20 11

**Comment by aevo98765** [comment]
@samarpita-bhaumik I have made the changes. Hopefully the lint process is clearer for you for in the future. If not I would be happy to chat. Thanks.

**Comment by samarpita-bhaumik** [comment]
@aevo98765 extremely sorry for the trouble actually I manually did lint correction for this file. Will surely check this from next time. Thank you so much for the help.😅

**Comment by vishnoianil** [comment]
@aevo98765 @samarpita-bhaumik the commit history of this PR doesn't look good to me. Looks like the main branch of the fork is pushed against the main branch of the ui repo, and that's causing the commit history issue where it endup making @samarpita-bhaumik co-author on 46 commits from different authors. I think we need to revert this and rebase it properly using a non-main branch.

**Comment by vishnoianil** [comment]
@aevo98765 @samarpita-bhaumik Looks like this PR merge re-added  some updated commit history. Looks like the PR was pushed from the main branch of the fork to the main branch of the UI repo. And I think fork's main branch was not rebased. This end-up updating around 46 commits from different authors and made @samarpita-bhaumik as a co-author to these commits. I am looking into fixing it.

@samarpita-bhaumik For future PR, please use the a separate branch in your local repo and push it against the upstream main branch, that way it only shows the commit that is being pushed to the local branch and keeps the commit history clean.

**Comment by aevo98765** [comment]
@samarpita-bhaumik would you be able to create a new branch and pull request and we will try this again! Sorry about all the confusion.

**Comment by samarpita-bhaumik** [comment]
@aevo98765 Sure I am creating another PR from a new branch

**Pull request merged**
